# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complete_task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flowable_sdk.model.flowable import process_variable_pb2 as flowable__sdk_dot_model_dot_flowable_dot_process__variable__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='complete_task.proto',
  package='task',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63omplete_task.proto\x12\x04task\x1a\x32\x66lowable_sdk/model/flowable/process_variable.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x82\x02\n\x13\x43ompleteTaskRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x10\n\x08\x61ssignee\x18\x03 \x01(\t\x12\x18\n\x10\x66ormDefinitionId\x18\x04 \x01(\t\x12\x0f\n\x07outcome\x18\x05 \x01(\t\x12\x34\n\tvariables\x18\x06 \x03(\x0b\x32!.flowable.FlowableProcessVariable\x12=\n\x12transientVariables\x18\x07 \x03(\x0b\x32!.flowable.FlowableProcessVariable\x12\x19\n\x11XXX_RestFieldMask\x18\x08 \x03(\t\"u\n\x1b\x43ompleteTaskResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12$\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[flowable__sdk_dot_model_dot_flowable_dot_process__variable__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_COMPLETETASKREQUEST = _descriptor.Descriptor(
  name='CompleteTaskRequest',
  full_name='task.CompleteTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='task.CompleteTaskRequest.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='task.CompleteTaskRequest.action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assignee', full_name='task.CompleteTaskRequest.assignee', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='formDefinitionId', full_name='task.CompleteTaskRequest.formDefinitionId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outcome', full_name='task.CompleteTaskRequest.outcome', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variables', full_name='task.CompleteTaskRequest.variables', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transientVariables', full_name='task.CompleteTaskRequest.transientVariables', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='XXX_RestFieldMask', full_name='task.CompleteTaskRequest.XXX_RestFieldMask', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=369,
)


_COMPLETETASKRESPONSEWRAPPER = _descriptor.Descriptor(
  name='CompleteTaskResponseWrapper',
  full_name='task.CompleteTaskResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='task.CompleteTaskResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='task.CompleteTaskResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='task.CompleteTaskResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='task.CompleteTaskResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=488,
)

_COMPLETETASKREQUEST.fields_by_name['variables'].message_type = flowable__sdk_dot_model_dot_flowable_dot_process__variable__pb2._FLOWABLEPROCESSVARIABLE
_COMPLETETASKREQUEST.fields_by_name['transientVariables'].message_type = flowable__sdk_dot_model_dot_flowable_dot_process__variable__pb2._FLOWABLEPROCESSVARIABLE
_COMPLETETASKRESPONSEWRAPPER.fields_by_name['data'].message_type = google_dot_protobuf_dot_empty__pb2._EMPTY
DESCRIPTOR.message_types_by_name['CompleteTaskRequest'] = _COMPLETETASKREQUEST
DESCRIPTOR.message_types_by_name['CompleteTaskResponseWrapper'] = _COMPLETETASKRESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompleteTaskRequest = _reflection.GeneratedProtocolMessageType('CompleteTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETETASKREQUEST,
  '__module__' : 'complete_task_pb2'
  # @@protoc_insertion_point(class_scope:task.CompleteTaskRequest)
  })
_sym_db.RegisterMessage(CompleteTaskRequest)

CompleteTaskResponseWrapper = _reflection.GeneratedProtocolMessageType('CompleteTaskResponseWrapper', (_message.Message,), {
  'DESCRIPTOR' : _COMPLETETASKRESPONSEWRAPPER,
  '__module__' : 'complete_task_pb2'
  # @@protoc_insertion_point(class_scope:task.CompleteTaskResponseWrapper)
  })
_sym_db.RegisterMessage(CompleteTaskResponseWrapper)


# @@protoc_insertion_point(module_scope)
