# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class FlowableProcessDefinition(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: typing___Text
    url = ... # type: typing___Text
    key = ... # type: typing___Text
    version = ... # type: builtin___int
    name = ... # type: typing___Text
    description = ... # type: typing___Text
    tenantId = ... # type: typing___Text
    deploymentId = ... # type: typing___Text
    deploymentUrl = ... # type: typing___Text
    resource = ... # type: typing___Text
    diagramResource = ... # type: typing___Text
    category = ... # type: typing___Text
    graphicalNotationDefinied = ... # type: builtin___bool
    suspended = ... # type: builtin___bool
    startFormDefined = ... # type: builtin___bool

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        url : typing___Optional[typing___Text] = None,
        key : typing___Optional[typing___Text] = None,
        version : typing___Optional[builtin___int] = None,
        name : typing___Optional[typing___Text] = None,
        description : typing___Optional[typing___Text] = None,
        tenantId : typing___Optional[typing___Text] = None,
        deploymentId : typing___Optional[typing___Text] = None,
        deploymentUrl : typing___Optional[typing___Text] = None,
        resource : typing___Optional[typing___Text] = None,
        diagramResource : typing___Optional[typing___Text] = None,
        category : typing___Optional[typing___Text] = None,
        graphicalNotationDefinied : typing___Optional[builtin___bool] = None,
        suspended : typing___Optional[builtin___bool] = None,
        startFormDefined : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> FlowableProcessDefinition: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> FlowableProcessDefinition: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"category",b"category",u"deploymentId",b"deploymentId",u"deploymentUrl",b"deploymentUrl",u"description",b"description",u"diagramResource",b"diagramResource",u"graphicalNotationDefinied",b"graphicalNotationDefinied",u"id",b"id",u"key",b"key",u"name",b"name",u"resource",b"resource",u"startFormDefined",b"startFormDefined",u"suspended",b"suspended",u"tenantId",b"tenantId",u"url",b"url",u"version",b"version"]) -> None: ...
