# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: callback_task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from model.easy_command import target_log_pb2 as model_dot_easy__command_dot_target__log__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='callback_task.proto',
  package='admin_task',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63\x61llback_task.proto\x12\nadmin_task\x1a#model/easy_command/target_log.proto\"\x83\x01\n\x18\x43\x61llbackAdminTaskRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x12+\n\ntargetsLog\x18\x04 \x03(\x0b\x32\x17.easy_command.TargetLog\x12\x0c\n\x04name\x18\x05 \x01(\t\"+\n\x19\x43\x61llbackAdminTaskResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x89\x01\n CallbackAdminTaskResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x33\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32%.admin_task.CallbackAdminTaskResponseb\x06proto3')
  ,
  dependencies=[model_dot_easy__command_dot_target__log__pb2.DESCRIPTOR,])




_CALLBACKADMINTASKREQUEST = _descriptor.Descriptor(
  name='CallbackAdminTaskRequest',
  full_name='admin_task.CallbackAdminTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='admin_task.CallbackAdminTaskRequest.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='admin_task.CallbackAdminTaskRequest.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='admin_task.CallbackAdminTaskRequest.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targetsLog', full_name='admin_task.CallbackAdminTaskRequest.targetsLog', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='admin_task.CallbackAdminTaskRequest.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=204,
)


_CALLBACKADMINTASKRESPONSE = _descriptor.Descriptor(
  name='CallbackAdminTaskResponse',
  full_name='admin_task.CallbackAdminTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='admin_task.CallbackAdminTaskResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=249,
)


_CALLBACKADMINTASKRESPONSEWRAPPER = _descriptor.Descriptor(
  name='CallbackAdminTaskResponseWrapper',
  full_name='admin_task.CallbackAdminTaskResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='admin_task.CallbackAdminTaskResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='admin_task.CallbackAdminTaskResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='admin_task.CallbackAdminTaskResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='admin_task.CallbackAdminTaskResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=389,
)

_CALLBACKADMINTASKREQUEST.fields_by_name['targetsLog'].message_type = model_dot_easy__command_dot_target__log__pb2._TARGETLOG
_CALLBACKADMINTASKRESPONSEWRAPPER.fields_by_name['data'].message_type = _CALLBACKADMINTASKRESPONSE
DESCRIPTOR.message_types_by_name['CallbackAdminTaskRequest'] = _CALLBACKADMINTASKREQUEST
DESCRIPTOR.message_types_by_name['CallbackAdminTaskResponse'] = _CALLBACKADMINTASKRESPONSE
DESCRIPTOR.message_types_by_name['CallbackAdminTaskResponseWrapper'] = _CALLBACKADMINTASKRESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CallbackAdminTaskRequest = _reflection.GeneratedProtocolMessageType('CallbackAdminTaskRequest', (_message.Message,), dict(
  DESCRIPTOR = _CALLBACKADMINTASKREQUEST,
  __module__ = 'callback_task_pb2'
  # @@protoc_insertion_point(class_scope:admin_task.CallbackAdminTaskRequest)
  ))
_sym_db.RegisterMessage(CallbackAdminTaskRequest)

CallbackAdminTaskResponse = _reflection.GeneratedProtocolMessageType('CallbackAdminTaskResponse', (_message.Message,), dict(
  DESCRIPTOR = _CALLBACKADMINTASKRESPONSE,
  __module__ = 'callback_task_pb2'
  # @@protoc_insertion_point(class_scope:admin_task.CallbackAdminTaskResponse)
  ))
_sym_db.RegisterMessage(CallbackAdminTaskResponse)

CallbackAdminTaskResponseWrapper = _reflection.GeneratedProtocolMessageType('CallbackAdminTaskResponseWrapper', (_message.Message,), dict(
  DESCRIPTOR = _CALLBACKADMINTASKRESPONSEWRAPPER,
  __module__ = 'callback_task_pb2'
  # @@protoc_insertion_point(class_scope:admin_task.CallbackAdminTaskResponseWrapper)
  ))
_sym_db.RegisterMessage(CallbackAdminTaskResponseWrapper)


# @@protoc_insertion_point(module_scope)
