# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class InstallPluginTaskV1Request(google___protobuf___message___Message):
    class DeployInfoList(google___protobuf___message___Message):
        agentId = ... # type: typing___Text
        ip = ... # type: typing___Text
        deployPath = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
        agentPluginId = ... # type: typing___Text
        agentPluginName = ... # type: typing___Text
        preVersionName = ... # type: typing___Text
        pluginVersionName = ... # type: typing___Text
        repoVersionId = ... # type: typing___Text

        def __init__(self,
            agentId : typing___Optional[typing___Text] = None,
            ip : typing___Optional[typing___Text] = None,
            deployPath : typing___Optional[typing___Iterable[typing___Text]] = None,
            agentPluginId : typing___Optional[typing___Text] = None,
            agentPluginName : typing___Optional[typing___Text] = None,
            preVersionName : typing___Optional[typing___Text] = None,
            pluginVersionName : typing___Optional[typing___Text] = None,
            repoVersionId : typing___Optional[typing___Text] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> InstallPluginTaskV1Request.DeployInfoList: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def ClearField(self, field_name: typing_extensions___Literal[u"agentId",u"agentPluginId",u"agentPluginName",u"deployPath",u"ip",u"pluginVersionName",u"preVersionName",u"repoVersionId"]) -> None: ...
        else:
            def ClearField(self, field_name: typing_extensions___Literal[b"agentId",b"agentPluginId",b"agentPluginName",b"deployPath",b"ip",b"pluginVersionName",b"preVersionName",b"repoVersionId"]) -> None: ...

    deployType = ... # type: typing___Text
    perBatchNum = ... # type: int
    perBatchInterval = ... # type: int

    @property
    def deployInfoList(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[InstallPluginTaskV1Request.DeployInfoList]: ...

    def __init__(self,
        deployInfoList : typing___Optional[typing___Iterable[InstallPluginTaskV1Request.DeployInfoList]] = None,
        deployType : typing___Optional[typing___Text] = None,
        perBatchNum : typing___Optional[int] = None,
        perBatchInterval : typing___Optional[int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> InstallPluginTaskV1Request: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"deployInfoList",u"deployType",u"perBatchInterval",u"perBatchNum"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"deployInfoList",b"deployType",b"perBatchInterval",b"perBatchNum"]) -> None: ...

class InstallPluginTaskV1Response(google___protobuf___message___Message):
    cmdTaskId = ... # type: typing___Text

    def __init__(self,
        cmdTaskId : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> InstallPluginTaskV1Response: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"cmdTaskId"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"cmdTaskId"]) -> None: ...

class InstallPluginTaskV1ResponseWrapper(google___protobuf___message___Message):
    code = ... # type: int
    codeExplain = ... # type: typing___Text
    error = ... # type: typing___Text

    @property
    def data(self) -> InstallPluginTaskV1Response: ...

    def __init__(self,
        code : typing___Optional[int] = None,
        codeExplain : typing___Optional[typing___Text] = None,
        error : typing___Optional[typing___Text] = None,
        data : typing___Optional[InstallPluginTaskV1Response] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> InstallPluginTaskV1ResponseWrapper: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"data"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"code",u"codeExplain",u"data",u"error"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"data",b"data"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[b"code",b"codeExplain",b"data",b"error"]) -> None: ...
