# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: install_plugin_v1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='install_plugin_v1.proto',
  package='admin_task',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17install_plugin_v1.proto\x12\nadmin_task\"\xec\x02\n\x1aInstallPluginTaskV1Request\x12M\n\x0e\x64\x65ployInfoList\x18\x01 \x03(\x0b\x32\x35.admin_task.InstallPluginTaskV1Request.DeployInfoList\x12\x12\n\ndeployType\x18\x02 \x01(\t\x12\x13\n\x0bperBatchNum\x18\x03 \x01(\x05\x12\x18\n\x10perBatchInterval\x18\x04 \x01(\x05\x1a\xbb\x01\n\x0e\x44\x65ployInfoList\x12\x0f\n\x07\x61gentId\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x12\n\ndeployPath\x18\x03 \x03(\t\x12\x15\n\ragentPluginId\x18\x04 \x01(\t\x12\x17\n\x0f\x61gentPluginName\x18\x05 \x01(\t\x12\x16\n\x0epreVersionName\x18\x06 \x01(\t\x12\x19\n\x11pluginVersionName\x18\x07 \x01(\t\x12\x15\n\rrepoVersionId\x18\x08 \x01(\t\"0\n\x1bInstallPluginTaskV1Response\x12\x11\n\tcmdTaskId\x18\x01 \x01(\t\"\x8d\x01\n\"InstallPluginTaskV1ResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x35\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\'.admin_task.InstallPluginTaskV1Responseb\x06proto3')
)




_INSTALLPLUGINTASKV1REQUEST_DEPLOYINFOLIST = _descriptor.Descriptor(
  name='DeployInfoList',
  full_name='admin_task.InstallPluginTaskV1Request.DeployInfoList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agentId', full_name='admin_task.InstallPluginTaskV1Request.DeployInfoList.agentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='admin_task.InstallPluginTaskV1Request.DeployInfoList.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deployPath', full_name='admin_task.InstallPluginTaskV1Request.DeployInfoList.deployPath', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agentPluginId', full_name='admin_task.InstallPluginTaskV1Request.DeployInfoList.agentPluginId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agentPluginName', full_name='admin_task.InstallPluginTaskV1Request.DeployInfoList.agentPluginName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preVersionName', full_name='admin_task.InstallPluginTaskV1Request.DeployInfoList.preVersionName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pluginVersionName', full_name='admin_task.InstallPluginTaskV1Request.DeployInfoList.pluginVersionName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repoVersionId', full_name='admin_task.InstallPluginTaskV1Request.DeployInfoList.repoVersionId', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=404,
)

_INSTALLPLUGINTASKV1REQUEST = _descriptor.Descriptor(
  name='InstallPluginTaskV1Request',
  full_name='admin_task.InstallPluginTaskV1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deployInfoList', full_name='admin_task.InstallPluginTaskV1Request.deployInfoList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deployType', full_name='admin_task.InstallPluginTaskV1Request.deployType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='perBatchNum', full_name='admin_task.InstallPluginTaskV1Request.perBatchNum', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='perBatchInterval', full_name='admin_task.InstallPluginTaskV1Request.perBatchInterval', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_INSTALLPLUGINTASKV1REQUEST_DEPLOYINFOLIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=404,
)


_INSTALLPLUGINTASKV1RESPONSE = _descriptor.Descriptor(
  name='InstallPluginTaskV1Response',
  full_name='admin_task.InstallPluginTaskV1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdTaskId', full_name='admin_task.InstallPluginTaskV1Response.cmdTaskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=454,
)


_INSTALLPLUGINTASKV1RESPONSEWRAPPER = _descriptor.Descriptor(
  name='InstallPluginTaskV1ResponseWrapper',
  full_name='admin_task.InstallPluginTaskV1ResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='admin_task.InstallPluginTaskV1ResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='admin_task.InstallPluginTaskV1ResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='admin_task.InstallPluginTaskV1ResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='admin_task.InstallPluginTaskV1ResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=598,
)

_INSTALLPLUGINTASKV1REQUEST_DEPLOYINFOLIST.containing_type = _INSTALLPLUGINTASKV1REQUEST
_INSTALLPLUGINTASKV1REQUEST.fields_by_name['deployInfoList'].message_type = _INSTALLPLUGINTASKV1REQUEST_DEPLOYINFOLIST
_INSTALLPLUGINTASKV1RESPONSEWRAPPER.fields_by_name['data'].message_type = _INSTALLPLUGINTASKV1RESPONSE
DESCRIPTOR.message_types_by_name['InstallPluginTaskV1Request'] = _INSTALLPLUGINTASKV1REQUEST
DESCRIPTOR.message_types_by_name['InstallPluginTaskV1Response'] = _INSTALLPLUGINTASKV1RESPONSE
DESCRIPTOR.message_types_by_name['InstallPluginTaskV1ResponseWrapper'] = _INSTALLPLUGINTASKV1RESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstallPluginTaskV1Request = _reflection.GeneratedProtocolMessageType('InstallPluginTaskV1Request', (_message.Message,), {

  'DeployInfoList' : _reflection.GeneratedProtocolMessageType('DeployInfoList', (_message.Message,), {
    'DESCRIPTOR' : _INSTALLPLUGINTASKV1REQUEST_DEPLOYINFOLIST,
    '__module__' : 'install_plugin_v1_pb2'
    # @@protoc_insertion_point(class_scope:admin_task.InstallPluginTaskV1Request.DeployInfoList)
    })
  ,
  'DESCRIPTOR' : _INSTALLPLUGINTASKV1REQUEST,
  '__module__' : 'install_plugin_v1_pb2'
  # @@protoc_insertion_point(class_scope:admin_task.InstallPluginTaskV1Request)
  })
_sym_db.RegisterMessage(InstallPluginTaskV1Request)
_sym_db.RegisterMessage(InstallPluginTaskV1Request.DeployInfoList)

InstallPluginTaskV1Response = _reflection.GeneratedProtocolMessageType('InstallPluginTaskV1Response', (_message.Message,), {
  'DESCRIPTOR' : _INSTALLPLUGINTASKV1RESPONSE,
  '__module__' : 'install_plugin_v1_pb2'
  # @@protoc_insertion_point(class_scope:admin_task.InstallPluginTaskV1Response)
  })
_sym_db.RegisterMessage(InstallPluginTaskV1Response)

InstallPluginTaskV1ResponseWrapper = _reflection.GeneratedProtocolMessageType('InstallPluginTaskV1ResponseWrapper', (_message.Message,), {
  'DESCRIPTOR' : _INSTALLPLUGINTASKV1RESPONSEWRAPPER,
  '__module__' : 'install_plugin_v1_pb2'
  # @@protoc_insertion_point(class_scope:admin_task.InstallPluginTaskV1ResponseWrapper)
  })
_sym_db.RegisterMessage(InstallPluginTaskV1ResponseWrapper)


# @@protoc_insertion_point(module_scope)
