# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_strategy_overview.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_strategy_overview.proto',
  package='datafilter',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bget_strategy_overview.proto\x12\ndatafilter\x1a\x1cgoogle/protobuf/struct.proto\"D\n\x1aGetStrategyOverviewRequest\x12&\n\x05query\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xe0\x01\n\x1bGetStrategyOverviewResponse\x12:\n\x04list\x18\x01 \x03(\x0b\x32,.datafilter.GetStrategyOverviewResponse.List\x1a\x84\x01\n\x04List\x12\x10\n\x08objectId\x18\x01 \x01(\t\x12\x15\n\rstrategyTotal\x18\x02 \x01(\x05\x12\x13\n\x0b\x65nableTotal\x18\x03 \x01(\x05\x12\x15\n\rexecFailTotal\x18\x04 \x01(\x05\x12\x11\n\texecTotal\x18\x05 \x01(\x05\x12\x14\n\x0clastExecTime\x18\x06 \x01(\t\"\x8d\x01\n\"GetStrategyOverviewResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x35\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\'.datafilter.GetStrategyOverviewResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_GETSTRATEGYOVERVIEWREQUEST = _descriptor.Descriptor(
  name='GetStrategyOverviewRequest',
  full_name='datafilter.GetStrategyOverviewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='datafilter.GetStrategyOverviewRequest.query', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=141,
)


_GETSTRATEGYOVERVIEWRESPONSE_LIST = _descriptor.Descriptor(
  name='List',
  full_name='datafilter.GetStrategyOverviewResponse.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objectId', full_name='datafilter.GetStrategyOverviewResponse.List.objectId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strategyTotal', full_name='datafilter.GetStrategyOverviewResponse.List.strategyTotal', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enableTotal', full_name='datafilter.GetStrategyOverviewResponse.List.enableTotal', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='execFailTotal', full_name='datafilter.GetStrategyOverviewResponse.List.execFailTotal', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='execTotal', full_name='datafilter.GetStrategyOverviewResponse.List.execTotal', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastExecTime', full_name='datafilter.GetStrategyOverviewResponse.List.lastExecTime', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=368,
)

_GETSTRATEGYOVERVIEWRESPONSE = _descriptor.Descriptor(
  name='GetStrategyOverviewResponse',
  full_name='datafilter.GetStrategyOverviewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='datafilter.GetStrategyOverviewResponse.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETSTRATEGYOVERVIEWRESPONSE_LIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=368,
)


_GETSTRATEGYOVERVIEWRESPONSEWRAPPER = _descriptor.Descriptor(
  name='GetStrategyOverviewResponseWrapper',
  full_name='datafilter.GetStrategyOverviewResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='datafilter.GetStrategyOverviewResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='datafilter.GetStrategyOverviewResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='datafilter.GetStrategyOverviewResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='datafilter.GetStrategyOverviewResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=512,
)

_GETSTRATEGYOVERVIEWREQUEST.fields_by_name['query'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GETSTRATEGYOVERVIEWRESPONSE_LIST.containing_type = _GETSTRATEGYOVERVIEWRESPONSE
_GETSTRATEGYOVERVIEWRESPONSE.fields_by_name['list'].message_type = _GETSTRATEGYOVERVIEWRESPONSE_LIST
_GETSTRATEGYOVERVIEWRESPONSEWRAPPER.fields_by_name['data'].message_type = _GETSTRATEGYOVERVIEWRESPONSE
DESCRIPTOR.message_types_by_name['GetStrategyOverviewRequest'] = _GETSTRATEGYOVERVIEWREQUEST
DESCRIPTOR.message_types_by_name['GetStrategyOverviewResponse'] = _GETSTRATEGYOVERVIEWRESPONSE
DESCRIPTOR.message_types_by_name['GetStrategyOverviewResponseWrapper'] = _GETSTRATEGYOVERVIEWRESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetStrategyOverviewRequest = _reflection.GeneratedProtocolMessageType('GetStrategyOverviewRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTRATEGYOVERVIEWREQUEST,
  '__module__' : 'get_strategy_overview_pb2'
  # @@protoc_insertion_point(class_scope:datafilter.GetStrategyOverviewRequest)
  })
_sym_db.RegisterMessage(GetStrategyOverviewRequest)

GetStrategyOverviewResponse = _reflection.GeneratedProtocolMessageType('GetStrategyOverviewResponse', (_message.Message,), {

  'List' : _reflection.GeneratedProtocolMessageType('List', (_message.Message,), {
    'DESCRIPTOR' : _GETSTRATEGYOVERVIEWRESPONSE_LIST,
    '__module__' : 'get_strategy_overview_pb2'
    # @@protoc_insertion_point(class_scope:datafilter.GetStrategyOverviewResponse.List)
    })
  ,
  'DESCRIPTOR' : _GETSTRATEGYOVERVIEWRESPONSE,
  '__module__' : 'get_strategy_overview_pb2'
  # @@protoc_insertion_point(class_scope:datafilter.GetStrategyOverviewResponse)
  })
_sym_db.RegisterMessage(GetStrategyOverviewResponse)
_sym_db.RegisterMessage(GetStrategyOverviewResponse.List)

GetStrategyOverviewResponseWrapper = _reflection.GeneratedProtocolMessageType('GetStrategyOverviewResponseWrapper', (_message.Message,), {
  'DESCRIPTOR' : _GETSTRATEGYOVERVIEWRESPONSEWRAPPER,
  '__module__' : 'get_strategy_overview_pb2'
  # @@protoc_insertion_point(class_scope:datafilter.GetStrategyOverviewResponseWrapper)
  })
_sym_db.RegisterMessage(GetStrategyOverviewResponseWrapper)


# @@protoc_insertion_point(module_scope)
