# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sort_single_storyboard.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from next_builder_sdk.model.next_builder import storyboard_brick_pb2 as next__builder__sdk_dot_model_dot_next__builder_dot_storyboard__brick__pb2
from next_builder_sdk.model.next_builder import storyboard_route_pb2 as next__builder__sdk_dot_model_dot_next__builder_dot_storyboard__route__pb2
from next_builder_sdk.model.next_builder import micro_app_project_pb2 as next__builder__sdk_dot_model_dot_next__builder_dot_micro__app__project__pb2
from next_builder_sdk.model.next_builder import storyboard_node_pb2 as next__builder__sdk_dot_model_dot_next__builder_dot_storyboard__node__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sort_single_storyboard.proto',
  package='storyboard',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1csort_single_storyboard.proto\x12\nstoryboard\x1a:next_builder_sdk/model/next_builder/storyboard_brick.proto\x1a:next_builder_sdk/model/next_builder/storyboard_route.proto\x1a;next_builder_sdk/model/next_builder/micro_app_project.proto\x1a\x39next_builder_sdk/model/next_builder/storyboard_node.proto\"K\n\x19SortStoryboardNodeRequest\x12\x12\n\ninstanceId\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04sort\x18\x03 \x01(\x05\"\x81\x01\n!SortStoryboardNodeResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12*\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x1c.next_builder.StoryboardNodeb\x06proto3')
  ,
  dependencies=[next__builder__sdk_dot_model_dot_next__builder_dot_storyboard__brick__pb2.DESCRIPTOR,next__builder__sdk_dot_model_dot_next__builder_dot_storyboard__route__pb2.DESCRIPTOR,next__builder__sdk_dot_model_dot_next__builder_dot_micro__app__project__pb2.DESCRIPTOR,next__builder__sdk_dot_model_dot_next__builder_dot_storyboard__node__pb2.DESCRIPTOR,])




_SORTSTORYBOARDNODEREQUEST = _descriptor.Descriptor(
  name='SortStoryboardNodeRequest',
  full_name='storyboard.SortStoryboardNodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='storyboard.SortStoryboardNodeRequest.instanceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='storyboard.SortStoryboardNodeRequest.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort', full_name='storyboard.SortStoryboardNodeRequest.sort', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=359,
)


_SORTSTORYBOARDNODERESPONSEWRAPPER = _descriptor.Descriptor(
  name='SortStoryboardNodeResponseWrapper',
  full_name='storyboard.SortStoryboardNodeResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='storyboard.SortStoryboardNodeResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='storyboard.SortStoryboardNodeResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='storyboard.SortStoryboardNodeResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='storyboard.SortStoryboardNodeResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=491,
)

_SORTSTORYBOARDNODERESPONSEWRAPPER.fields_by_name['data'].message_type = next__builder__sdk_dot_model_dot_next__builder_dot_storyboard__node__pb2._STORYBOARDNODE
DESCRIPTOR.message_types_by_name['SortStoryboardNodeRequest'] = _SORTSTORYBOARDNODEREQUEST
DESCRIPTOR.message_types_by_name['SortStoryboardNodeResponseWrapper'] = _SORTSTORYBOARDNODERESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SortStoryboardNodeRequest = _reflection.GeneratedProtocolMessageType('SortStoryboardNodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SORTSTORYBOARDNODEREQUEST,
  '__module__' : 'sort_single_storyboard_pb2'
  # @@protoc_insertion_point(class_scope:storyboard.SortStoryboardNodeRequest)
  })
_sym_db.RegisterMessage(SortStoryboardNodeRequest)

SortStoryboardNodeResponseWrapper = _reflection.GeneratedProtocolMessageType('SortStoryboardNodeResponseWrapper', (_message.Message,), {
  'DESCRIPTOR' : _SORTSTORYBOARDNODERESPONSEWRAPPER,
  '__module__' : 'sort_single_storyboard_pb2'
  # @@protoc_insertion_point(class_scope:storyboard.SortStoryboardNodeResponseWrapper)
  })
_sym_db.RegisterMessage(SortStoryboardNodeResponseWrapper)


# @@protoc_insertion_point(module_scope)
