# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from flowable_service_sdk.model.flowable_service.process_variable_pb2 import (
    ProcessVariable as flowable_service_sdk___model___flowable_service___process_variable_pb2___ProcessVariable,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class GetProcessInstanceRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    instanceId = ... # type: typing___Text

    def __init__(self,
        *,
        instanceId : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GetProcessInstanceRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetProcessInstanceRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"instanceId",b"instanceId"]) -> None: ...

class GetProcessInstanceResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class ProcessVersion(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        instanceId = ... # type: typing___Text
        versionName = ... # type: typing___Text

        def __init__(self,
            *,
            instanceId : typing___Optional[typing___Text] = None,
            versionName : typing___Optional[typing___Text] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> GetProcessInstanceResponse.ProcessVersion: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetProcessInstanceResponse.ProcessVersion: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"instanceId",b"instanceId",u"versionName",b"versionName"]) -> None: ...

    class Process(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        instanceId = ... # type: typing___Text
        name = ... # type: typing___Text
        category = ... # type: typing___Text

        def __init__(self,
            *,
            instanceId : typing___Optional[typing___Text] = None,
            name : typing___Optional[typing___Text] = None,
            category : typing___Optional[typing___Text] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> GetProcessInstanceResponse.Process: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetProcessInstanceResponse.Process: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"category",b"category",u"instanceId",b"instanceId",u"name",b"name"]) -> None: ...

    class UserTaskList(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class ProcessOp(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            name = ... # type: typing___Text
            targetTaskId = ... # type: typing___Text

            @property
            def conditionExpression(self) -> flowable_service_sdk___model___flowable_service___process_variable_pb2___ProcessVariable: ...

            def __init__(self,
                *,
                name : typing___Optional[typing___Text] = None,
                conditionExpression : typing___Optional[flowable_service_sdk___model___flowable_service___process_variable_pb2___ProcessVariable] = None,
                targetTaskId : typing___Optional[typing___Text] = None,
                ) -> None: ...
            if sys.version_info >= (3,):
                @classmethod
                def FromString(cls, s: builtin___bytes) -> GetProcessInstanceResponse.UserTaskList.ProcessOp: ...
            else:
                @classmethod
                def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetProcessInstanceResponse.UserTaskList.ProcessOp: ...
            def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
            def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
            def HasField(self, field_name: typing_extensions___Literal[u"conditionExpression",b"conditionExpression"]) -> builtin___bool: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"conditionExpression",b"conditionExpression",u"name",b"name",u"targetTaskId",b"targetTaskId"]) -> None: ...

        id = ... # type: typing___Text
        name = ... # type: typing___Text
        formDefinition = ... # type: typing___Text
        isFormDecision = ... # type: typing___Text

        @property
        def processOp(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[GetProcessInstanceResponse.UserTaskList.ProcessOp]: ...

        def __init__(self,
            *,
            id : typing___Optional[typing___Text] = None,
            name : typing___Optional[typing___Text] = None,
            formDefinition : typing___Optional[typing___Text] = None,
            isFormDecision : typing___Optional[typing___Text] = None,
            processOp : typing___Optional[typing___Iterable[GetProcessInstanceResponse.UserTaskList.ProcessOp]] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> GetProcessInstanceResponse.UserTaskList: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetProcessInstanceResponse.UserTaskList: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"formDefinition",b"formDefinition",u"id",b"id",u"isFormDecision",b"isFormDecision",u"name",b"name",u"processOp",b"processOp"]) -> None: ...

    class StepList(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        class FormData(google___protobuf___message___Message):
            DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
            header = ... # type: typing___Text
            body = ... # type: typing___Text

            def __init__(self,
                *,
                header : typing___Optional[typing___Text] = None,
                body : typing___Optional[typing___Text] = None,
                ) -> None: ...
            if sys.version_info >= (3,):
                @classmethod
                def FromString(cls, s: builtin___bytes) -> GetProcessInstanceResponse.StepList.FormData: ...
            else:
                @classmethod
                def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetProcessInstanceResponse.StepList.FormData: ...
            def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
            def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
            def ClearField(self, field_name: typing_extensions___Literal[u"body",b"body",u"header",b"header"]) -> None: ...

        userTaskId = ... # type: typing___Text
        operator = ... # type: typing___Text
        otime = ... # type: typing___Text
        action = ... # type: typing___Text
        memo = ... # type: typing___Text
        status = ... # type: typing___Text

        @property
        def formData(self) -> GetProcessInstanceResponse.StepList.FormData: ...

        def __init__(self,
            *,
            userTaskId : typing___Optional[typing___Text] = None,
            formData : typing___Optional[GetProcessInstanceResponse.StepList.FormData] = None,
            operator : typing___Optional[typing___Text] = None,
            otime : typing___Optional[typing___Text] = None,
            action : typing___Optional[typing___Text] = None,
            memo : typing___Optional[typing___Text] = None,
            status : typing___Optional[typing___Text] = None,
            ) -> None: ...
        if sys.version_info >= (3,):
            @classmethod
            def FromString(cls, s: builtin___bytes) -> GetProcessInstanceResponse.StepList: ...
        else:
            @classmethod
            def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetProcessInstanceResponse.StepList: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def HasField(self, field_name: typing_extensions___Literal[u"formData",b"formData"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"action",b"action",u"formData",b"formData",u"memo",b"memo",u"operator",b"operator",u"otime",b"otime",u"status",b"status",u"userTaskId",b"userTaskId"]) -> None: ...

    finishedStepList = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    instanceId = ... # type: typing___Text
    flowableInstanceId = ... # type: typing___Text
    name = ... # type: typing___Text
    creator = ... # type: typing___Text
    ctime = ... # type: typing___Text
    etime = ... # type: typing___Text
    status = ... # type: typing___Text
    stepIdList = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    stopAt = ... # type: typing___Text
    isSuspended = ... # type: builtin___bool
    isCancelled = ... # type: builtin___bool

    @property
    def processVersion(self) -> GetProcessInstanceResponse.ProcessVersion: ...

    @property
    def process(self) -> GetProcessInstanceResponse.Process: ...

    @property
    def userTaskList(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[GetProcessInstanceResponse.UserTaskList]: ...

    @property
    def stepList(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[GetProcessInstanceResponse.StepList]: ...

    def __init__(self,
        *,
        processVersion : typing___Optional[GetProcessInstanceResponse.ProcessVersion] = None,
        process : typing___Optional[GetProcessInstanceResponse.Process] = None,
        userTaskList : typing___Optional[typing___Iterable[GetProcessInstanceResponse.UserTaskList]] = None,
        stepList : typing___Optional[typing___Iterable[GetProcessInstanceResponse.StepList]] = None,
        finishedStepList : typing___Optional[typing___Iterable[typing___Text]] = None,
        instanceId : typing___Optional[typing___Text] = None,
        flowableInstanceId : typing___Optional[typing___Text] = None,
        name : typing___Optional[typing___Text] = None,
        creator : typing___Optional[typing___Text] = None,
        ctime : typing___Optional[typing___Text] = None,
        etime : typing___Optional[typing___Text] = None,
        status : typing___Optional[typing___Text] = None,
        stepIdList : typing___Optional[typing___Iterable[typing___Text]] = None,
        stopAt : typing___Optional[typing___Text] = None,
        isSuspended : typing___Optional[builtin___bool] = None,
        isCancelled : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GetProcessInstanceResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetProcessInstanceResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"process",b"process",u"processVersion",b"processVersion"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"creator",b"creator",u"ctime",b"ctime",u"etime",b"etime",u"finishedStepList",b"finishedStepList",u"flowableInstanceId",b"flowableInstanceId",u"instanceId",b"instanceId",u"isCancelled",b"isCancelled",u"isSuspended",b"isSuspended",u"name",b"name",u"process",b"process",u"processVersion",b"processVersion",u"status",b"status",u"stepIdList",b"stepIdList",u"stepList",b"stepList",u"stopAt",b"stopAt",u"userTaskList",b"userTaskList"]) -> None: ...

class GetProcessInstanceResponseWrapper(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    code = ... # type: builtin___int
    codeExplain = ... # type: typing___Text
    error = ... # type: typing___Text

    @property
    def data(self) -> GetProcessInstanceResponse: ...

    def __init__(self,
        *,
        code : typing___Optional[builtin___int] = None,
        codeExplain : typing___Optional[typing___Text] = None,
        error : typing___Optional[typing___Text] = None,
        data : typing___Optional[GetProcessInstanceResponse] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GetProcessInstanceResponseWrapper: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetProcessInstanceResponseWrapper: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"data",b"data"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"code",b"code",u"codeExplain",b"codeExplain",u"data",b"data",u"error",b"error"]) -> None: ...
