# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_process_instance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='start_process_instance.proto',
  package='process_instance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1cstart_process_instance.proto\x12\x10process_instance\"\xb9\x01\n\x1bStartProcessInstanceRequest\x12\x18\n\x10processVersionId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12H\n\x08\x66ormData\x18\x03 \x01(\x0b\x32\x36.process_instance.StartProcessInstanceRequest.FormData\x1a(\n\x08\x46ormData\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\"\xfa\x04\n\x1cStartProcessInstanceResponse\x12Q\n\x0cuserTaskList\x18\x01 \x03(\x0b\x32;.process_instance.StartProcessInstanceResponse.UserTaskList\x12I\n\x08stepList\x18\x02 \x03(\x0b\x32\x37.process_instance.StartProcessInstanceResponse.StepList\x12\x12\n\ninstanceId\x18\x03 \x01(\t\x12\x1a\n\x12\x66lowableInstanceId\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0f\n\x07\x63reator\x18\x06 \x01(\t\x12\r\n\x05\x63time\x18\x07 \x01(\t\x12\r\n\x05\x65time\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\x12\x12\n\nstepIdList\x18\n \x03(\t\x12\x0e\n\x06stopAt\x18\x0b \x01(\t\x12\x13\n\x0bisSuspended\x18\x0c \x01(\x08\x12\x13\n\x0bisCancelled\x18\r \x01(\x08\x1a@\n\x0cUserTaskList\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x66ormDefinition\x18\x03 \x01(\t\x1a\xae\x01\n\x08StepList\x12\x12\n\nuserTaskId\x18\x01 \x01(\t\x12\x10\n\x08\x61ssignee\x18\x02 \x01(\t\x12R\n\x08\x66ormData\x18\x03 \x01(\x0b\x32@.process_instance.StartProcessInstanceResponse.StepList.FormData\x1a(\n\x08\x46ormData\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\"\x95\x01\n#StartProcessInstanceResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12<\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32..process_instance.StartProcessInstanceResponseb\x06proto3')
)




_STARTPROCESSINSTANCEREQUEST_FORMDATA = _descriptor.Descriptor(
  name='FormData',
  full_name='process_instance.StartProcessInstanceRequest.FormData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='process_instance.StartProcessInstanceRequest.FormData.header', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='process_instance.StartProcessInstanceRequest.FormData.body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=236,
)

_STARTPROCESSINSTANCEREQUEST = _descriptor.Descriptor(
  name='StartProcessInstanceRequest',
  full_name='process_instance.StartProcessInstanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='processVersionId', full_name='process_instance.StartProcessInstanceRequest.processVersionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='process_instance.StartProcessInstanceRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='formData', full_name='process_instance.StartProcessInstanceRequest.formData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STARTPROCESSINSTANCEREQUEST_FORMDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=236,
)


_STARTPROCESSINSTANCERESPONSE_USERTASKLIST = _descriptor.Descriptor(
  name='UserTaskList',
  full_name='process_instance.StartProcessInstanceResponse.UserTaskList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='process_instance.StartProcessInstanceResponse.UserTaskList.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='process_instance.StartProcessInstanceResponse.UserTaskList.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='formDefinition', full_name='process_instance.StartProcessInstanceResponse.UserTaskList.formDefinition', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=632,
  serialized_end=696,
)

_STARTPROCESSINSTANCERESPONSE_STEPLIST_FORMDATA = _descriptor.Descriptor(
  name='FormData',
  full_name='process_instance.StartProcessInstanceResponse.StepList.FormData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='process_instance.StartProcessInstanceResponse.StepList.FormData.header', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='process_instance.StartProcessInstanceResponse.StepList.FormData.body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=236,
)

_STARTPROCESSINSTANCERESPONSE_STEPLIST = _descriptor.Descriptor(
  name='StepList',
  full_name='process_instance.StartProcessInstanceResponse.StepList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userTaskId', full_name='process_instance.StartProcessInstanceResponse.StepList.userTaskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assignee', full_name='process_instance.StartProcessInstanceResponse.StepList.assignee', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='formData', full_name='process_instance.StartProcessInstanceResponse.StepList.formData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STARTPROCESSINSTANCERESPONSE_STEPLIST_FORMDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=699,
  serialized_end=873,
)

_STARTPROCESSINSTANCERESPONSE = _descriptor.Descriptor(
  name='StartProcessInstanceResponse',
  full_name='process_instance.StartProcessInstanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userTaskList', full_name='process_instance.StartProcessInstanceResponse.userTaskList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stepList', full_name='process_instance.StartProcessInstanceResponse.stepList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instanceId', full_name='process_instance.StartProcessInstanceResponse.instanceId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flowableInstanceId', full_name='process_instance.StartProcessInstanceResponse.flowableInstanceId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='process_instance.StartProcessInstanceResponse.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creator', full_name='process_instance.StartProcessInstanceResponse.creator', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ctime', full_name='process_instance.StartProcessInstanceResponse.ctime', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='etime', full_name='process_instance.StartProcessInstanceResponse.etime', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='process_instance.StartProcessInstanceResponse.status', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stepIdList', full_name='process_instance.StartProcessInstanceResponse.stepIdList', index=9,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stopAt', full_name='process_instance.StartProcessInstanceResponse.stopAt', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isSuspended', full_name='process_instance.StartProcessInstanceResponse.isSuspended', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isCancelled', full_name='process_instance.StartProcessInstanceResponse.isCancelled', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STARTPROCESSINSTANCERESPONSE_USERTASKLIST, _STARTPROCESSINSTANCERESPONSE_STEPLIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=873,
)


_STARTPROCESSINSTANCERESPONSEWRAPPER = _descriptor.Descriptor(
  name='StartProcessInstanceResponseWrapper',
  full_name='process_instance.StartProcessInstanceResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='process_instance.StartProcessInstanceResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='process_instance.StartProcessInstanceResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='process_instance.StartProcessInstanceResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='process_instance.StartProcessInstanceResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=876,
  serialized_end=1025,
)

_STARTPROCESSINSTANCEREQUEST_FORMDATA.containing_type = _STARTPROCESSINSTANCEREQUEST
_STARTPROCESSINSTANCEREQUEST.fields_by_name['formData'].message_type = _STARTPROCESSINSTANCEREQUEST_FORMDATA
_STARTPROCESSINSTANCERESPONSE_USERTASKLIST.containing_type = _STARTPROCESSINSTANCERESPONSE
_STARTPROCESSINSTANCERESPONSE_STEPLIST_FORMDATA.containing_type = _STARTPROCESSINSTANCERESPONSE_STEPLIST
_STARTPROCESSINSTANCERESPONSE_STEPLIST.fields_by_name['formData'].message_type = _STARTPROCESSINSTANCERESPONSE_STEPLIST_FORMDATA
_STARTPROCESSINSTANCERESPONSE_STEPLIST.containing_type = _STARTPROCESSINSTANCERESPONSE
_STARTPROCESSINSTANCERESPONSE.fields_by_name['userTaskList'].message_type = _STARTPROCESSINSTANCERESPONSE_USERTASKLIST
_STARTPROCESSINSTANCERESPONSE.fields_by_name['stepList'].message_type = _STARTPROCESSINSTANCERESPONSE_STEPLIST
_STARTPROCESSINSTANCERESPONSEWRAPPER.fields_by_name['data'].message_type = _STARTPROCESSINSTANCERESPONSE
DESCRIPTOR.message_types_by_name['StartProcessInstanceRequest'] = _STARTPROCESSINSTANCEREQUEST
DESCRIPTOR.message_types_by_name['StartProcessInstanceResponse'] = _STARTPROCESSINSTANCERESPONSE
DESCRIPTOR.message_types_by_name['StartProcessInstanceResponseWrapper'] = _STARTPROCESSINSTANCERESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartProcessInstanceRequest = _reflection.GeneratedProtocolMessageType('StartProcessInstanceRequest', (_message.Message,), {

  'FormData' : _reflection.GeneratedProtocolMessageType('FormData', (_message.Message,), {
    'DESCRIPTOR' : _STARTPROCESSINSTANCEREQUEST_FORMDATA,
    '__module__' : 'start_process_instance_pb2'
    # @@protoc_insertion_point(class_scope:process_instance.StartProcessInstanceRequest.FormData)
    })
  ,
  'DESCRIPTOR' : _STARTPROCESSINSTANCEREQUEST,
  '__module__' : 'start_process_instance_pb2'
  # @@protoc_insertion_point(class_scope:process_instance.StartProcessInstanceRequest)
  })
_sym_db.RegisterMessage(StartProcessInstanceRequest)
_sym_db.RegisterMessage(StartProcessInstanceRequest.FormData)

StartProcessInstanceResponse = _reflection.GeneratedProtocolMessageType('StartProcessInstanceResponse', (_message.Message,), {

  'UserTaskList' : _reflection.GeneratedProtocolMessageType('UserTaskList', (_message.Message,), {
    'DESCRIPTOR' : _STARTPROCESSINSTANCERESPONSE_USERTASKLIST,
    '__module__' : 'start_process_instance_pb2'
    # @@protoc_insertion_point(class_scope:process_instance.StartProcessInstanceResponse.UserTaskList)
    })
  ,

  'StepList' : _reflection.GeneratedProtocolMessageType('StepList', (_message.Message,), {

    'FormData' : _reflection.GeneratedProtocolMessageType('FormData', (_message.Message,), {
      'DESCRIPTOR' : _STARTPROCESSINSTANCERESPONSE_STEPLIST_FORMDATA,
      '__module__' : 'start_process_instance_pb2'
      # @@protoc_insertion_point(class_scope:process_instance.StartProcessInstanceResponse.StepList.FormData)
      })
    ,
    'DESCRIPTOR' : _STARTPROCESSINSTANCERESPONSE_STEPLIST,
    '__module__' : 'start_process_instance_pb2'
    # @@protoc_insertion_point(class_scope:process_instance.StartProcessInstanceResponse.StepList)
    })
  ,
  'DESCRIPTOR' : _STARTPROCESSINSTANCERESPONSE,
  '__module__' : 'start_process_instance_pb2'
  # @@protoc_insertion_point(class_scope:process_instance.StartProcessInstanceResponse)
  })
_sym_db.RegisterMessage(StartProcessInstanceResponse)
_sym_db.RegisterMessage(StartProcessInstanceResponse.UserTaskList)
_sym_db.RegisterMessage(StartProcessInstanceResponse.StepList)
_sym_db.RegisterMessage(StartProcessInstanceResponse.StepList.FormData)

StartProcessInstanceResponseWrapper = _reflection.GeneratedProtocolMessageType('StartProcessInstanceResponseWrapper', (_message.Message,), {
  'DESCRIPTOR' : _STARTPROCESSINSTANCERESPONSEWRAPPER,
  '__module__' : 'start_process_instance_pb2'
  # @@protoc_insertion_point(class_scope:process_instance.StartProcessInstanceResponseWrapper)
  })
_sym_db.RegisterMessage(StartProcessInstanceResponseWrapper)


# @@protoc_insertion_point(module_scope)
