# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list_process_instance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flowable_sdk.model.flowable import process_instance_pb2 as flowable__sdk_dot_model_dot_flowable_dot_process__instance__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='list_process_instance.proto',
  package='process_instance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1blist_process_instance.proto\x12\x10process_instance\x1a\x32\x66lowable_sdk/model/flowable/process_instance.proto\"\xb3\x01\n\x1aListProcessInstanceRequest\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x13\n\x0b\x62usinessKey\x18\x05 \x01(\t\x12\x11\n\tsuspended\x18\x06 \x01(\t\x12\x1b\n\x13processDefinitionId\x18\x07 \x01(\t\x12\x19\n\x11XXX_RestFieldMask\x18\x08 \x03(\t\"\x97\x01\n\x1bListProcessInstanceResponse\x12/\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32!.flowable.FlowableProcessInstance\x12\r\n\x05total\x18\x02 \x01(\x05\x12\r\n\x05start\x18\x03 \x01(\x05\x12\x0c\n\x04sort\x18\x04 \x01(\t\x12\r\n\x05order\x18\x05 \x01(\t\x12\x0c\n\x04size\x18\x06 \x01(\x05\"\x93\x01\n\"ListProcessInstanceResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12;\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32-.process_instance.ListProcessInstanceResponseb\x06proto3')
  ,
  dependencies=[flowable__sdk_dot_model_dot_flowable_dot_process__instance__pb2.DESCRIPTOR,])




_LISTPROCESSINSTANCEREQUEST = _descriptor.Descriptor(
  name='ListProcessInstanceRequest',
  full_name='process_instance.ListProcessInstanceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='process_instance.ListProcessInstanceRequest.start', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='process_instance.ListProcessInstanceRequest.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='process_instance.ListProcessInstanceRequest.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='process_instance.ListProcessInstanceRequest.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='businessKey', full_name='process_instance.ListProcessInstanceRequest.businessKey', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='suspended', full_name='process_instance.ListProcessInstanceRequest.suspended', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='processDefinitionId', full_name='process_instance.ListProcessInstanceRequest.processDefinitionId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='XXX_RestFieldMask', full_name='process_instance.ListProcessInstanceRequest.XXX_RestFieldMask', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=281,
)


_LISTPROCESSINSTANCERESPONSE = _descriptor.Descriptor(
  name='ListProcessInstanceResponse',
  full_name='process_instance.ListProcessInstanceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='process_instance.ListProcessInstanceResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='process_instance.ListProcessInstanceResponse.total', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='process_instance.ListProcessInstanceResponse.start', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort', full_name='process_instance.ListProcessInstanceResponse.sort', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order', full_name='process_instance.ListProcessInstanceResponse.order', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='process_instance.ListProcessInstanceResponse.size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=435,
)


_LISTPROCESSINSTANCERESPONSEWRAPPER = _descriptor.Descriptor(
  name='ListProcessInstanceResponseWrapper',
  full_name='process_instance.ListProcessInstanceResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='process_instance.ListProcessInstanceResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='process_instance.ListProcessInstanceResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='process_instance.ListProcessInstanceResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='process_instance.ListProcessInstanceResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=585,
)

_LISTPROCESSINSTANCERESPONSE.fields_by_name['data'].message_type = flowable__sdk_dot_model_dot_flowable_dot_process__instance__pb2._FLOWABLEPROCESSINSTANCE
_LISTPROCESSINSTANCERESPONSEWRAPPER.fields_by_name['data'].message_type = _LISTPROCESSINSTANCERESPONSE
DESCRIPTOR.message_types_by_name['ListProcessInstanceRequest'] = _LISTPROCESSINSTANCEREQUEST
DESCRIPTOR.message_types_by_name['ListProcessInstanceResponse'] = _LISTPROCESSINSTANCERESPONSE
DESCRIPTOR.message_types_by_name['ListProcessInstanceResponseWrapper'] = _LISTPROCESSINSTANCERESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListProcessInstanceRequest = _reflection.GeneratedProtocolMessageType('ListProcessInstanceRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTPROCESSINSTANCEREQUEST,
  '__module__' : 'list_process_instance_pb2'
  # @@protoc_insertion_point(class_scope:process_instance.ListProcessInstanceRequest)
  })
_sym_db.RegisterMessage(ListProcessInstanceRequest)

ListProcessInstanceResponse = _reflection.GeneratedProtocolMessageType('ListProcessInstanceResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTPROCESSINSTANCERESPONSE,
  '__module__' : 'list_process_instance_pb2'
  # @@protoc_insertion_point(class_scope:process_instance.ListProcessInstanceResponse)
  })
_sym_db.RegisterMessage(ListProcessInstanceResponse)

ListProcessInstanceResponseWrapper = _reflection.GeneratedProtocolMessageType('ListProcessInstanceResponseWrapper', (_message.Message,), {
  'DESCRIPTOR' : _LISTPROCESSINSTANCERESPONSEWRAPPER,
  '__module__' : 'list_process_instance_pb2'
  # @@protoc_insertion_point(class_scope:process_instance.ListProcessInstanceResponseWrapper)
  })
_sym_db.RegisterMessage(ListProcessInstanceResponseWrapper)


# @@protoc_insertion_point(module_scope)
