# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: create_from_yaml.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from container_sdk.model.container import service_spec_pb2 as container__sdk_dot_model_dot_container_dot_service__spec__pb2
from container_sdk.model.container import loadbalancer_status_pb2 as container__sdk_dot_model_dot_container_dot_loadbalancer__status__pb2
from container_sdk.model.container import service_pb2 as container__sdk_dot_model_dot_container_dot_service__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='create_from_yaml.proto',
  package='service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63reate_from_yaml.proto\x12\x07service\x1a\x30\x63ontainer_sdk/model/container/service_spec.proto\x1a\x37\x63ontainer_sdk/model/container/loadbalancer_status.proto\x1a+container_sdk/model/container/service.proto\x1a\x1cgoogle/protobuf/struct.proto\";\n\x15\x43reateFromYamlRequest\x12\x0c\n\x04rgId\x18\x01 \x01(\t\x12\x14\n\x0cresourceSpec\x18\x02 \x01(\t\"s\n\x1d\x43reateFromYamlResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12 \n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x12.container.Serviceb\x06proto3')
  ,
  dependencies=[container__sdk_dot_model_dot_container_dot_service__spec__pb2.DESCRIPTOR,container__sdk_dot_model_dot_container_dot_loadbalancer__status__pb2.DESCRIPTOR,container__sdk_dot_model_dot_container_dot_service__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_CREATEFROMYAMLREQUEST = _descriptor.Descriptor(
  name='CreateFromYamlRequest',
  full_name='service.CreateFromYamlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rgId', full_name='service.CreateFromYamlRequest.rgId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resourceSpec', full_name='service.CreateFromYamlRequest.resourceSpec', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=276,
)


_CREATEFROMYAMLRESPONSEWRAPPER = _descriptor.Descriptor(
  name='CreateFromYamlResponseWrapper',
  full_name='service.CreateFromYamlResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='service.CreateFromYamlResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='service.CreateFromYamlResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='service.CreateFromYamlResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='service.CreateFromYamlResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=393,
)

_CREATEFROMYAMLRESPONSEWRAPPER.fields_by_name['data'].message_type = container__sdk_dot_model_dot_container_dot_service__pb2._SERVICE
DESCRIPTOR.message_types_by_name['CreateFromYamlRequest'] = _CREATEFROMYAMLREQUEST
DESCRIPTOR.message_types_by_name['CreateFromYamlResponseWrapper'] = _CREATEFROMYAMLRESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateFromYamlRequest = _reflection.GeneratedProtocolMessageType('CreateFromYamlRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEFROMYAMLREQUEST,
  '__module__' : 'create_from_yaml_pb2'
  # @@protoc_insertion_point(class_scope:service.CreateFromYamlRequest)
  })
_sym_db.RegisterMessage(CreateFromYamlRequest)

CreateFromYamlResponseWrapper = _reflection.GeneratedProtocolMessageType('CreateFromYamlResponseWrapper', (_message.Message,), {
  'DESCRIPTOR' : _CREATEFROMYAMLRESPONSEWRAPPER,
  '__module__' : 'create_from_yaml_pb2'
  # @@protoc_insertion_point(class_scope:service.CreateFromYamlResponseWrapper)
  })
_sym_db.RegisterMessage(CreateFromYamlResponseWrapper)


# @@protoc_insertion_point(module_scope)
