# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_job_table_tool.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_job_table_tool.proto',
  package='job_export',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18get_job_table_tool.proto\x12\njob_export\x1a\x1cgoogle/protobuf/struct.proto\"3\n\x1aGetJobTableToolJsonRequest\x12\x15\n\rjobTaskIdTool\x18\x01 \x01(\t\"\xd5\x04\n\x1bGetJobTableToolJsonResponse\x12*\n\tstartTime\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12(\n\x07\x65ndTime\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\'\n\x06status\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12*\n\ttableData\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x10\n\x08username\x18\x05 \x01(\t\x12\x44\n\ttableDefs\x18\x06 \x03(\x0b\x32\x31.job_export.GetJobTableToolJsonResponse.TableDefs\x12\x0b\n\x03vId\x18\x07 \x01(\t\x12\x13\n\x0btotalStatus\x18\x08 \x01(\t\x1a\x90\x02\n\tTableDefs\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12P\n\ndimensions\x18\x03 \x03(\x0b\x32<.job_export.GetJobTableToolJsonResponse.TableDefs.Dimensions\x12J\n\x07\x63olumns\x18\x04 \x03(\x0b\x32\x39.job_export.GetJobTableToolJsonResponse.TableDefs.Columns\x1a&\n\nDimensions\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x1a#\n\x07\x43olumns\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x8d\x01\n\"GetJobTableToolJsonResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x35\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\'.job_export.GetJobTableToolJsonResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_GETJOBTABLETOOLJSONREQUEST = _descriptor.Descriptor(
  name='GetJobTableToolJsonRequest',
  full_name='job_export.GetJobTableToolJsonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobTaskIdTool', full_name='job_export.GetJobTableToolJsonRequest.jobTaskIdTool', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=121,
)


_GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS_DIMENSIONS = _descriptor.Descriptor(
  name='Dimensions',
  full_name='job_export.GetJobTableToolJsonResponse.TableDefs.Dimensions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='job_export.GetJobTableToolJsonResponse.TableDefs.Dimensions.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='job_export.GetJobTableToolJsonResponse.TableDefs.Dimensions.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=646,
  serialized_end=684,
)

_GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS_COLUMNS = _descriptor.Descriptor(
  name='Columns',
  full_name='job_export.GetJobTableToolJsonResponse.TableDefs.Columns',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='job_export.GetJobTableToolJsonResponse.TableDefs.Columns.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='job_export.GetJobTableToolJsonResponse.TableDefs.Columns.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=721,
)

_GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS = _descriptor.Descriptor(
  name='TableDefs',
  full_name='job_export.GetJobTableToolJsonResponse.TableDefs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='job_export.GetJobTableToolJsonResponse.TableDefs.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='job_export.GetJobTableToolJsonResponse.TableDefs.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='job_export.GetJobTableToolJsonResponse.TableDefs.dimensions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='columns', full_name='job_export.GetJobTableToolJsonResponse.TableDefs.columns', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS_DIMENSIONS, _GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS_COLUMNS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=721,
)

_GETJOBTABLETOOLJSONRESPONSE = _descriptor.Descriptor(
  name='GetJobTableToolJsonResponse',
  full_name='job_export.GetJobTableToolJsonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startTime', full_name='job_export.GetJobTableToolJsonResponse.startTime', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endTime', full_name='job_export.GetJobTableToolJsonResponse.endTime', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='job_export.GetJobTableToolJsonResponse.status', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tableData', full_name='job_export.GetJobTableToolJsonResponse.tableData', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='job_export.GetJobTableToolJsonResponse.username', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tableDefs', full_name='job_export.GetJobTableToolJsonResponse.tableDefs', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vId', full_name='job_export.GetJobTableToolJsonResponse.vId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalStatus', full_name='job_export.GetJobTableToolJsonResponse.totalStatus', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=721,
)


_GETJOBTABLETOOLJSONRESPONSEWRAPPER = _descriptor.Descriptor(
  name='GetJobTableToolJsonResponseWrapper',
  full_name='job_export.GetJobTableToolJsonResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='job_export.GetJobTableToolJsonResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='job_export.GetJobTableToolJsonResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='job_export.GetJobTableToolJsonResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='job_export.GetJobTableToolJsonResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=724,
  serialized_end=865,
)

_GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS_DIMENSIONS.containing_type = _GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS
_GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS_COLUMNS.containing_type = _GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS
_GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS.fields_by_name['dimensions'].message_type = _GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS_DIMENSIONS
_GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS.fields_by_name['columns'].message_type = _GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS_COLUMNS
_GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS.containing_type = _GETJOBTABLETOOLJSONRESPONSE
_GETJOBTABLETOOLJSONRESPONSE.fields_by_name['startTime'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GETJOBTABLETOOLJSONRESPONSE.fields_by_name['endTime'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GETJOBTABLETOOLJSONRESPONSE.fields_by_name['status'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GETJOBTABLETOOLJSONRESPONSE.fields_by_name['tableData'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GETJOBTABLETOOLJSONRESPONSE.fields_by_name['tableDefs'].message_type = _GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS
_GETJOBTABLETOOLJSONRESPONSEWRAPPER.fields_by_name['data'].message_type = _GETJOBTABLETOOLJSONRESPONSE
DESCRIPTOR.message_types_by_name['GetJobTableToolJsonRequest'] = _GETJOBTABLETOOLJSONREQUEST
DESCRIPTOR.message_types_by_name['GetJobTableToolJsonResponse'] = _GETJOBTABLETOOLJSONRESPONSE
DESCRIPTOR.message_types_by_name['GetJobTableToolJsonResponseWrapper'] = _GETJOBTABLETOOLJSONRESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetJobTableToolJsonRequest = _reflection.GeneratedProtocolMessageType('GetJobTableToolJsonRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETJOBTABLETOOLJSONREQUEST,
  __module__ = 'get_job_table_tool_pb2'
  # @@protoc_insertion_point(class_scope:job_export.GetJobTableToolJsonRequest)
  ))
_sym_db.RegisterMessage(GetJobTableToolJsonRequest)

GetJobTableToolJsonResponse = _reflection.GeneratedProtocolMessageType('GetJobTableToolJsonResponse', (_message.Message,), dict(

  TableDefs = _reflection.GeneratedProtocolMessageType('TableDefs', (_message.Message,), dict(

    Dimensions = _reflection.GeneratedProtocolMessageType('Dimensions', (_message.Message,), dict(
      DESCRIPTOR = _GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS_DIMENSIONS,
      __module__ = 'get_job_table_tool_pb2'
      # @@protoc_insertion_point(class_scope:job_export.GetJobTableToolJsonResponse.TableDefs.Dimensions)
      ))
    ,

    Columns = _reflection.GeneratedProtocolMessageType('Columns', (_message.Message,), dict(
      DESCRIPTOR = _GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS_COLUMNS,
      __module__ = 'get_job_table_tool_pb2'
      # @@protoc_insertion_point(class_scope:job_export.GetJobTableToolJsonResponse.TableDefs.Columns)
      ))
    ,
    DESCRIPTOR = _GETJOBTABLETOOLJSONRESPONSE_TABLEDEFS,
    __module__ = 'get_job_table_tool_pb2'
    # @@protoc_insertion_point(class_scope:job_export.GetJobTableToolJsonResponse.TableDefs)
    ))
  ,
  DESCRIPTOR = _GETJOBTABLETOOLJSONRESPONSE,
  __module__ = 'get_job_table_tool_pb2'
  # @@protoc_insertion_point(class_scope:job_export.GetJobTableToolJsonResponse)
  ))
_sym_db.RegisterMessage(GetJobTableToolJsonResponse)
_sym_db.RegisterMessage(GetJobTableToolJsonResponse.TableDefs)
_sym_db.RegisterMessage(GetJobTableToolJsonResponse.TableDefs.Dimensions)
_sym_db.RegisterMessage(GetJobTableToolJsonResponse.TableDefs.Columns)

GetJobTableToolJsonResponseWrapper = _reflection.GeneratedProtocolMessageType('GetJobTableToolJsonResponseWrapper', (_message.Message,), dict(
  DESCRIPTOR = _GETJOBTABLETOOLJSONRESPONSEWRAPPER,
  __module__ = 'get_job_table_tool_pb2'
  # @@protoc_insertion_point(class_scope:job_export.GetJobTableToolJsonResponseWrapper)
  ))
_sym_db.RegisterMessage(GetJobTableToolJsonResponseWrapper)


# @@protoc_insertion_point(module_scope)
