# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update_task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from patch_manager_sdk.model.easy_command import task_callback_pb2 as patch__manager__sdk_dot_model_dot_easy__command_dot_task__callback__pb2
from patch_manager_sdk.model.easy_command import target_log_pb2 as patch__manager__sdk_dot_model_dot_easy__command_dot_target__log__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='update_task.proto',
  package='patch_task',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11update_task.proto\x12\npatch_task\x1a\x38patch_manager_sdk/model/easy_command/task_callback.proto\x1a\x35patch_manager_sdk/model/easy_command/target_log.proto\"/\n\x1dHostPatchTaskCallbackResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x91\x01\n$HostPatchTaskCallbackResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x37\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32).patch_task.HostPatchTaskCallbackResponseb\x06proto3')
  ,
  dependencies=[patch__manager__sdk_dot_model_dot_easy__command_dot_task__callback__pb2.DESCRIPTOR,patch__manager__sdk_dot_model_dot_easy__command_dot_target__log__pb2.DESCRIPTOR,])




_HOSTPATCHTASKCALLBACKRESPONSE = _descriptor.Descriptor(
  name='HostPatchTaskCallbackResponse',
  full_name='patch_task.HostPatchTaskCallbackResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='patch_task.HostPatchTaskCallbackResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=193,
)


_HOSTPATCHTASKCALLBACKRESPONSEWRAPPER = _descriptor.Descriptor(
  name='HostPatchTaskCallbackResponseWrapper',
  full_name='patch_task.HostPatchTaskCallbackResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='patch_task.HostPatchTaskCallbackResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='patch_task.HostPatchTaskCallbackResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='patch_task.HostPatchTaskCallbackResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='patch_task.HostPatchTaskCallbackResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=341,
)

_HOSTPATCHTASKCALLBACKRESPONSEWRAPPER.fields_by_name['data'].message_type = _HOSTPATCHTASKCALLBACKRESPONSE
DESCRIPTOR.message_types_by_name['HostPatchTaskCallbackResponse'] = _HOSTPATCHTASKCALLBACKRESPONSE
DESCRIPTOR.message_types_by_name['HostPatchTaskCallbackResponseWrapper'] = _HOSTPATCHTASKCALLBACKRESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HostPatchTaskCallbackResponse = _reflection.GeneratedProtocolMessageType('HostPatchTaskCallbackResponse', (_message.Message,), {
  'DESCRIPTOR' : _HOSTPATCHTASKCALLBACKRESPONSE,
  '__module__' : 'update_task_pb2'
  # @@protoc_insertion_point(class_scope:patch_task.HostPatchTaskCallbackResponse)
  })
_sym_db.RegisterMessage(HostPatchTaskCallbackResponse)

HostPatchTaskCallbackResponseWrapper = _reflection.GeneratedProtocolMessageType('HostPatchTaskCallbackResponseWrapper', (_message.Message,), {
  'DESCRIPTOR' : _HOSTPATCHTASKCALLBACKRESPONSEWRAPPER,
  '__module__' : 'update_task_pb2'
  # @@protoc_insertion_point(class_scope:patch_task.HostPatchTaskCallbackResponseWrapper)
  })
_sym_db.RegisterMessage(HostPatchTaskCallbackResponseWrapper)


# @@protoc_insertion_point(module_scope)
