# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list_plugin_v1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='list_plugin_v1.proto',
  package='plugin',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14list_plugin_v1.proto\x12\x06plugin\"5\n\x13ListPluginV1Request\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\"\x8f\x04\n\x14ListPluginV1Response\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12/\n\x04list\x18\x04 \x03(\x0b\x32!.plugin.ListPluginV1Response.List\x1a\x95\x03\n\x04List\x12H\n\x0elastestVersion\x18\x01 \x01(\x0b\x32\x30.plugin.ListPluginV1Response.List.LastestVersion\x12\x15\n\rdeployedCount\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x12\n\ndeployPath\x18\x05 \x03(\t\x12\x0c\n\x04memo\x18\x06 \x01(\t\x12\x15\n\rrepoPackageId\x18\x07 \x01(\t\x12\x0f\n\x07\x63reator\x18\x08 \x01(\t\x12\r\n\x05\x63time\x18\t \x01(\x05\x12\r\n\x05mtime\x18\n \x01(\x05\x12\x10\n\x08isLocked\x18\x0b \x01(\x08\x1a\x97\x01\n\x0eLastestVersion\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rrepoVersionId\x18\x02 \x01(\t\x12\x13\n\x0bversionName\x18\x03 \x01(\t\x12\x0c\n\x04memo\x18\x04 \x01(\t\x12\x10\n\x08pluginId\x18\x05 \x01(\t\x12\x0f\n\x07\x63reator\x18\x06 \x01(\t\x12\r\n\x05\x63time\x18\x07 \x01(\x05\x12\r\n\x05mtime\x18\x08 \x01(\x05\"{\n\x1bListPluginV1ResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12*\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x1c.plugin.ListPluginV1Responseb\x06proto3')
)




_LISTPLUGINV1REQUEST = _descriptor.Descriptor(
  name='ListPluginV1Request',
  full_name='plugin.ListPluginV1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='plugin.ListPluginV1Request.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='plugin.ListPluginV1Request.pageSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=85,
)


_LISTPLUGINV1RESPONSE_LIST_LASTESTVERSION = _descriptor.Descriptor(
  name='LastestVersion',
  full_name='plugin.ListPluginV1Response.List.LastestVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='plugin.ListPluginV1Response.List.LastestVersion.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repoVersionId', full_name='plugin.ListPluginV1Response.List.LastestVersion.repoVersionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionName', full_name='plugin.ListPluginV1Response.List.LastestVersion.versionName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='plugin.ListPluginV1Response.List.LastestVersion.memo', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pluginId', full_name='plugin.ListPluginV1Response.List.LastestVersion.pluginId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creator', full_name='plugin.ListPluginV1Response.List.LastestVersion.creator', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ctime', full_name='plugin.ListPluginV1Response.List.LastestVersion.ctime', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mtime', full_name='plugin.ListPluginV1Response.List.LastestVersion.mtime', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=615,
)

_LISTPLUGINV1RESPONSE_LIST = _descriptor.Descriptor(
  name='List',
  full_name='plugin.ListPluginV1Response.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lastestVersion', full_name='plugin.ListPluginV1Response.List.lastestVersion', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deployedCount', full_name='plugin.ListPluginV1Response.List.deployedCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='plugin.ListPluginV1Response.List.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='plugin.ListPluginV1Response.List.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deployPath', full_name='plugin.ListPluginV1Response.List.deployPath', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='plugin.ListPluginV1Response.List.memo', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repoPackageId', full_name='plugin.ListPluginV1Response.List.repoPackageId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creator', full_name='plugin.ListPluginV1Response.List.creator', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ctime', full_name='plugin.ListPluginV1Response.List.ctime', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mtime', full_name='plugin.ListPluginV1Response.List.mtime', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isLocked', full_name='plugin.ListPluginV1Response.List.isLocked', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LISTPLUGINV1RESPONSE_LIST_LASTESTVERSION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=615,
)

_LISTPLUGINV1RESPONSE = _descriptor.Descriptor(
  name='ListPluginV1Response',
  full_name='plugin.ListPluginV1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='plugin.ListPluginV1Response.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='plugin.ListPluginV1Response.page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='plugin.ListPluginV1Response.total', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list', full_name='plugin.ListPluginV1Response.list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LISTPLUGINV1RESPONSE_LIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=615,
)


_LISTPLUGINV1RESPONSEWRAPPER = _descriptor.Descriptor(
  name='ListPluginV1ResponseWrapper',
  full_name='plugin.ListPluginV1ResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='plugin.ListPluginV1ResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='plugin.ListPluginV1ResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='plugin.ListPluginV1ResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='plugin.ListPluginV1ResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=740,
)

_LISTPLUGINV1RESPONSE_LIST_LASTESTVERSION.containing_type = _LISTPLUGINV1RESPONSE_LIST
_LISTPLUGINV1RESPONSE_LIST.fields_by_name['lastestVersion'].message_type = _LISTPLUGINV1RESPONSE_LIST_LASTESTVERSION
_LISTPLUGINV1RESPONSE_LIST.containing_type = _LISTPLUGINV1RESPONSE
_LISTPLUGINV1RESPONSE.fields_by_name['list'].message_type = _LISTPLUGINV1RESPONSE_LIST
_LISTPLUGINV1RESPONSEWRAPPER.fields_by_name['data'].message_type = _LISTPLUGINV1RESPONSE
DESCRIPTOR.message_types_by_name['ListPluginV1Request'] = _LISTPLUGINV1REQUEST
DESCRIPTOR.message_types_by_name['ListPluginV1Response'] = _LISTPLUGINV1RESPONSE
DESCRIPTOR.message_types_by_name['ListPluginV1ResponseWrapper'] = _LISTPLUGINV1RESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListPluginV1Request = _reflection.GeneratedProtocolMessageType('ListPluginV1Request', (_message.Message,), {
  'DESCRIPTOR' : _LISTPLUGINV1REQUEST,
  '__module__' : 'list_plugin_v1_pb2'
  # @@protoc_insertion_point(class_scope:plugin.ListPluginV1Request)
  })
_sym_db.RegisterMessage(ListPluginV1Request)

ListPluginV1Response = _reflection.GeneratedProtocolMessageType('ListPluginV1Response', (_message.Message,), {

  'List' : _reflection.GeneratedProtocolMessageType('List', (_message.Message,), {

    'LastestVersion' : _reflection.GeneratedProtocolMessageType('LastestVersion', (_message.Message,), {
      'DESCRIPTOR' : _LISTPLUGINV1RESPONSE_LIST_LASTESTVERSION,
      '__module__' : 'list_plugin_v1_pb2'
      # @@protoc_insertion_point(class_scope:plugin.ListPluginV1Response.List.LastestVersion)
      })
    ,
    'DESCRIPTOR' : _LISTPLUGINV1RESPONSE_LIST,
    '__module__' : 'list_plugin_v1_pb2'
    # @@protoc_insertion_point(class_scope:plugin.ListPluginV1Response.List)
    })
  ,
  'DESCRIPTOR' : _LISTPLUGINV1RESPONSE,
  '__module__' : 'list_plugin_v1_pb2'
  # @@protoc_insertion_point(class_scope:plugin.ListPluginV1Response)
  })
_sym_db.RegisterMessage(ListPluginV1Response)
_sym_db.RegisterMessage(ListPluginV1Response.List)
_sym_db.RegisterMessage(ListPluginV1Response.List.LastestVersion)

ListPluginV1ResponseWrapper = _reflection.GeneratedProtocolMessageType('ListPluginV1ResponseWrapper', (_message.Message,), {
  'DESCRIPTOR' : _LISTPLUGINV1RESPONSEWRAPPER,
  '__module__' : 'list_plugin_v1_pb2'
  # @@protoc_insertion_point(class_scope:plugin.ListPluginV1ResponseWrapper)
  })
_sym_db.RegisterMessage(ListPluginV1ResponseWrapper)


# @@protoc_insertion_point(module_scope)
