# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list_plugin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from model.agent_admin import plugin_pb2 as model_dot_agent__admin_dot_plugin__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='list_plugin.proto',
  package='plugin',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11list_plugin.proto\x12\x06plugin\x1a\x1emodel/agent_admin/plugin.proto\"3\n\x11ListPluginRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\"g\n\x12ListPluginResponse\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12!\n\x04list\x18\x04 \x03(\x0b\x32\x13.agent_admin.Plugin\"w\n\x19ListPluginResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12(\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x1a.plugin.ListPluginResponseb\x06proto3')
  ,
  dependencies=[model_dot_agent__admin_dot_plugin__pb2.DESCRIPTOR,])




_LISTPLUGINREQUEST = _descriptor.Descriptor(
  name='ListPluginRequest',
  full_name='plugin.ListPluginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='plugin.ListPluginRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='plugin.ListPluginRequest.pageSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=112,
)


_LISTPLUGINRESPONSE = _descriptor.Descriptor(
  name='ListPluginResponse',
  full_name='plugin.ListPluginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='plugin.ListPluginResponse.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='plugin.ListPluginResponse.page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='plugin.ListPluginResponse.total', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list', full_name='plugin.ListPluginResponse.list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=217,
)


_LISTPLUGINRESPONSEWRAPPER = _descriptor.Descriptor(
  name='ListPluginResponseWrapper',
  full_name='plugin.ListPluginResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='plugin.ListPluginResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='plugin.ListPluginResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='plugin.ListPluginResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='plugin.ListPluginResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=338,
)

_LISTPLUGINRESPONSE.fields_by_name['list'].message_type = model_dot_agent__admin_dot_plugin__pb2._PLUGIN
_LISTPLUGINRESPONSEWRAPPER.fields_by_name['data'].message_type = _LISTPLUGINRESPONSE
DESCRIPTOR.message_types_by_name['ListPluginRequest'] = _LISTPLUGINREQUEST
DESCRIPTOR.message_types_by_name['ListPluginResponse'] = _LISTPLUGINRESPONSE
DESCRIPTOR.message_types_by_name['ListPluginResponseWrapper'] = _LISTPLUGINRESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListPluginRequest = _reflection.GeneratedProtocolMessageType('ListPluginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTPLUGINREQUEST,
  __module__ = 'list_plugin_pb2'
  # @@protoc_insertion_point(class_scope:plugin.ListPluginRequest)
  ))
_sym_db.RegisterMessage(ListPluginRequest)

ListPluginResponse = _reflection.GeneratedProtocolMessageType('ListPluginResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTPLUGINRESPONSE,
  __module__ = 'list_plugin_pb2'
  # @@protoc_insertion_point(class_scope:plugin.ListPluginResponse)
  ))
_sym_db.RegisterMessage(ListPluginResponse)

ListPluginResponseWrapper = _reflection.GeneratedProtocolMessageType('ListPluginResponseWrapper', (_message.Message,), dict(
  DESCRIPTOR = _LISTPLUGINRESPONSEWRAPPER,
  __module__ = 'list_plugin_pb2'
  # @@protoc_insertion_point(class_scope:plugin.ListPluginResponseWrapper)
  ))
_sym_db.RegisterMessage(ListPluginResponseWrapper)


# @@protoc_insertion_point(module_scope)
