# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Plugin(google___protobuf___message___Message):
    id = ... # type: typing___Text
    name = ... # type: typing___Text
    deployPath = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    memo = ... # type: typing___Text
    repoPackageId = ... # type: typing___Text
    creator = ... # type: typing___Text
    ctime = ... # type: int
    mtime = ... # type: int
    isLocked = ... # type: bool

    def __init__(self,
        id : typing___Optional[typing___Text] = None,
        name : typing___Optional[typing___Text] = None,
        deployPath : typing___Optional[typing___Iterable[typing___Text]] = None,
        memo : typing___Optional[typing___Text] = None,
        repoPackageId : typing___Optional[typing___Text] = None,
        creator : typing___Optional[typing___Text] = None,
        ctime : typing___Optional[int] = None,
        mtime : typing___Optional[int] = None,
        isLocked : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Plugin: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"creator",u"ctime",u"deployPath",u"id",u"isLocked",u"memo",u"mtime",u"name",u"repoPackageId"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"creator",b"ctime",b"deployPath",b"id",b"isLocked",b"memo",b"mtime",b"name",b"repoPackageId"]) -> None: ...
