# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: update.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='update.proto',
  package='sqlpkg_versions',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cupdate.proto\x12\x0fsqlpkg_versions\"\xde\x01\n\x1eUpdateSQLPackageVersionRequest\x12\r\n\x05pkgId\x18\x01 \x01(\t\x12\x11\n\tversionId\x18\x02 \x01(\t\x12`\n\x13updateSqlPkgVersion\x18\x03 \x01(\x0b\x32\x43.sqlpkg_versions.UpdateSQLPackageVersionRequest.UpdateSqlPkgVersion\x1a\x38\n\x13UpdateSqlPkgVersion\x12\x0c\n\x04memo\x18\x01 \x01(\t\x12\x13\n\x0bversionType\x18\x02 \x01(\t\"\xf7\x02\n\x1fUpdateSQLPackageVersionResponse\x12O\n\nsqlPackage\x18\x01 \x01(\x0b\x32;.sqlpkg_versions.UpdateSQLPackageVersionResponse.SqlPackage\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x15\n\rrepoVersionId\x18\x04 \x01(\t\x12\x13\n\x0bversionName\x18\x05 \x01(\t\x12\x0c\n\x04memo\x18\x06 \x01(\t\x12\x0f\n\x07\x63reator\x18\x07 \x01(\t\x12\r\n\x05\x63time\x18\x08 \x01(\x03\x12\r\n\x05mtime\x18\t \x01(\x03\x12\x13\n\x0bversionType\x18\n \x01(\t\x1ak\n\nSqlPackage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04memo\x18\x03 \x01(\t\x12\x15\n\rrepoPackageId\x18\x04 \x01(\t\x12\x0f\n\x07\x63reator\x18\x05 \x01(\t\x12\r\n\x05mtime\x18\x06 \x01(\x03\"\x9a\x01\n&UpdateSQLPackageVersionResponseWrapper\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63odeExplain\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12>\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x30.sqlpkg_versions.UpdateSQLPackageVersionResponseb\x06proto3')
)




_UPDATESQLPACKAGEVERSIONREQUEST_UPDATESQLPKGVERSION = _descriptor.Descriptor(
  name='UpdateSqlPkgVersion',
  full_name='sqlpkg_versions.UpdateSQLPackageVersionRequest.UpdateSqlPkgVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='memo', full_name='sqlpkg_versions.UpdateSQLPackageVersionRequest.UpdateSqlPkgVersion.memo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionType', full_name='sqlpkg_versions.UpdateSQLPackageVersionRequest.UpdateSqlPkgVersion.versionType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=256,
)

_UPDATESQLPACKAGEVERSIONREQUEST = _descriptor.Descriptor(
  name='UpdateSQLPackageVersionRequest',
  full_name='sqlpkg_versions.UpdateSQLPackageVersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pkgId', full_name='sqlpkg_versions.UpdateSQLPackageVersionRequest.pkgId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionId', full_name='sqlpkg_versions.UpdateSQLPackageVersionRequest.versionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updateSqlPkgVersion', full_name='sqlpkg_versions.UpdateSQLPackageVersionRequest.updateSqlPkgVersion', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UPDATESQLPACKAGEVERSIONREQUEST_UPDATESQLPKGVERSION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=256,
)


_UPDATESQLPACKAGEVERSIONRESPONSE_SQLPACKAGE = _descriptor.Descriptor(
  name='SqlPackage',
  full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.SqlPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.SqlPackage.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.SqlPackage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.SqlPackage.memo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repoPackageId', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.SqlPackage.repoPackageId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creator', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.SqlPackage.creator', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mtime', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.SqlPackage.mtime', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=634,
)

_UPDATESQLPACKAGEVERSIONRESPONSE = _descriptor.Descriptor(
  name='UpdateSQLPackageVersionResponse',
  full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sqlPackage', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.sqlPackage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repoVersionId', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.repoVersionId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionName', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.versionName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.memo', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creator', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.creator', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ctime', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.ctime', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mtime', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.mtime', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='versionType', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponse.versionType', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_UPDATESQLPACKAGEVERSIONRESPONSE_SQLPACKAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=634,
)


_UPDATESQLPACKAGEVERSIONRESPONSEWRAPPER = _descriptor.Descriptor(
  name='UpdateSQLPackageVersionResponseWrapper',
  full_name='sqlpkg_versions.UpdateSQLPackageVersionResponseWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponseWrapper.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codeExplain', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponseWrapper.codeExplain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponseWrapper.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='sqlpkg_versions.UpdateSQLPackageVersionResponseWrapper.data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=637,
  serialized_end=791,
)

_UPDATESQLPACKAGEVERSIONREQUEST_UPDATESQLPKGVERSION.containing_type = _UPDATESQLPACKAGEVERSIONREQUEST
_UPDATESQLPACKAGEVERSIONREQUEST.fields_by_name['updateSqlPkgVersion'].message_type = _UPDATESQLPACKAGEVERSIONREQUEST_UPDATESQLPKGVERSION
_UPDATESQLPACKAGEVERSIONRESPONSE_SQLPACKAGE.containing_type = _UPDATESQLPACKAGEVERSIONRESPONSE
_UPDATESQLPACKAGEVERSIONRESPONSE.fields_by_name['sqlPackage'].message_type = _UPDATESQLPACKAGEVERSIONRESPONSE_SQLPACKAGE
_UPDATESQLPACKAGEVERSIONRESPONSEWRAPPER.fields_by_name['data'].message_type = _UPDATESQLPACKAGEVERSIONRESPONSE
DESCRIPTOR.message_types_by_name['UpdateSQLPackageVersionRequest'] = _UPDATESQLPACKAGEVERSIONREQUEST
DESCRIPTOR.message_types_by_name['UpdateSQLPackageVersionResponse'] = _UPDATESQLPACKAGEVERSIONRESPONSE
DESCRIPTOR.message_types_by_name['UpdateSQLPackageVersionResponseWrapper'] = _UPDATESQLPACKAGEVERSIONRESPONSEWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateSQLPackageVersionRequest = _reflection.GeneratedProtocolMessageType('UpdateSQLPackageVersionRequest', (_message.Message,), {

  'UpdateSqlPkgVersion' : _reflection.GeneratedProtocolMessageType('UpdateSqlPkgVersion', (_message.Message,), {
    'DESCRIPTOR' : _UPDATESQLPACKAGEVERSIONREQUEST_UPDATESQLPKGVERSION,
    '__module__' : 'update_pb2'
    # @@protoc_insertion_point(class_scope:sqlpkg_versions.UpdateSQLPackageVersionRequest.UpdateSqlPkgVersion)
    })
  ,
  'DESCRIPTOR' : _UPDATESQLPACKAGEVERSIONREQUEST,
  '__module__' : 'update_pb2'
  # @@protoc_insertion_point(class_scope:sqlpkg_versions.UpdateSQLPackageVersionRequest)
  })
_sym_db.RegisterMessage(UpdateSQLPackageVersionRequest)
_sym_db.RegisterMessage(UpdateSQLPackageVersionRequest.UpdateSqlPkgVersion)

UpdateSQLPackageVersionResponse = _reflection.GeneratedProtocolMessageType('UpdateSQLPackageVersionResponse', (_message.Message,), {

  'SqlPackage' : _reflection.GeneratedProtocolMessageType('SqlPackage', (_message.Message,), {
    'DESCRIPTOR' : _UPDATESQLPACKAGEVERSIONRESPONSE_SQLPACKAGE,
    '__module__' : 'update_pb2'
    # @@protoc_insertion_point(class_scope:sqlpkg_versions.UpdateSQLPackageVersionResponse.SqlPackage)
    })
  ,
  'DESCRIPTOR' : _UPDATESQLPACKAGEVERSIONRESPONSE,
  '__module__' : 'update_pb2'
  # @@protoc_insertion_point(class_scope:sqlpkg_versions.UpdateSQLPackageVersionResponse)
  })
_sym_db.RegisterMessage(UpdateSQLPackageVersionResponse)
_sym_db.RegisterMessage(UpdateSQLPackageVersionResponse.SqlPackage)

UpdateSQLPackageVersionResponseWrapper = _reflection.GeneratedProtocolMessageType('UpdateSQLPackageVersionResponseWrapper', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESQLPACKAGEVERSIONRESPONSEWRAPPER,
  '__module__' : 'update_pb2'
  # @@protoc_insertion_point(class_scope:sqlpkg_versions.UpdateSQLPackageVersionResponseWrapper)
  })
_sym_db.RegisterMessage(UpdateSQLPackageVersionResponseWrapper)


# @@protoc_insertion_point(module_scope)
