# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class InstanceInfo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    instanceId = ... # type: builtin___int
    packageId = ... # type: typing___Text
    versionId = ... # type: typing___Text
    deviceId = ... # type: typing___Text
    installPath = ... # type: typing___Text
    creator = ... # type: typing___Text
    packageName = ... # type: typing___Text
    packageType = ... # type: builtin___int
    versionName = ... # type: typing___Text
    deviceIp = ... # type: typing___Text
    org = ... # type: builtin___int
    installTime = ... # type: typing___Text
    updateTime = ... # type: typing___Text
    ctime = ... # type: typing___Text
    mtime = ... # type: typing___Text
    appId = ... # type: typing___Text
    clusterId = ... # type: typing___Text
    lastOperation = ... # type: typing___Text
    configId = ... # type: typing___Text
    configPackageId = ... # type: typing___Text
    hostInstanceId = ... # type: typing___Text

    def __init__(self,
        *,
        instanceId : typing___Optional[builtin___int] = None,
        packageId : typing___Optional[typing___Text] = None,
        versionId : typing___Optional[typing___Text] = None,
        deviceId : typing___Optional[typing___Text] = None,
        installPath : typing___Optional[typing___Text] = None,
        creator : typing___Optional[typing___Text] = None,
        packageName : typing___Optional[typing___Text] = None,
        packageType : typing___Optional[builtin___int] = None,
        versionName : typing___Optional[typing___Text] = None,
        deviceIp : typing___Optional[typing___Text] = None,
        org : typing___Optional[builtin___int] = None,
        installTime : typing___Optional[typing___Text] = None,
        updateTime : typing___Optional[typing___Text] = None,
        ctime : typing___Optional[typing___Text] = None,
        mtime : typing___Optional[typing___Text] = None,
        appId : typing___Optional[typing___Text] = None,
        clusterId : typing___Optional[typing___Text] = None,
        lastOperation : typing___Optional[typing___Text] = None,
        configId : typing___Optional[typing___Text] = None,
        configPackageId : typing___Optional[typing___Text] = None,
        hostInstanceId : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> InstanceInfo: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> InstanceInfo: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"appId",b"appId",u"clusterId",b"clusterId",u"configId",b"configId",u"configPackageId",b"configPackageId",u"creator",b"creator",u"ctime",b"ctime",u"deviceId",b"deviceId",u"deviceIp",b"deviceIp",u"hostInstanceId",b"hostInstanceId",u"installPath",b"installPath",u"installTime",b"installTime",u"instanceId",b"instanceId",u"lastOperation",b"lastOperation",u"mtime",b"mtime",u"org",b"org",u"packageId",b"packageId",u"packageName",b"packageName",u"packageType",b"packageType",u"updateTime",b"updateTime",u"versionId",b"versionId",u"versionName",b"versionName"]) -> None: ...
