# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class FilterStrategyInstance(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: typing___Text
    strategyId = ... # type: typing___Text
    strategyObjectId = ... # type: typing___Text
    ctime = ... # type: typing___Text
    etime = ... # type: typing___Text
    total = ... # type: builtin___int
    failCount = ... # type: builtin___int
    status = ... # type: typing___Text
    message = ... # type: typing___Text

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        strategyId : typing___Optional[typing___Text] = None,
        strategyObjectId : typing___Optional[typing___Text] = None,
        ctime : typing___Optional[typing___Text] = None,
        etime : typing___Optional[typing___Text] = None,
        total : typing___Optional[builtin___int] = None,
        failCount : typing___Optional[builtin___int] = None,
        status : typing___Optional[typing___Text] = None,
        message : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> FilterStrategyInstance: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> FilterStrategyInstance: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"ctime",b"ctime",u"etime",b"etime",u"failCount",b"failCount",u"id",b"id",u"message",b"message",u"status",b"status",u"strategyId",b"strategyId",u"strategyObjectId",b"strategyObjectId",u"total",b"total"]) -> None: ...
